src/Contracts/ItemHistoryWidget.php

In the UML the function should be like this:
`addEdit(AdminUser $saved_by, DateTime $saved_at)`
But I thought that all actions performed on an item might not necessarily be a kind of edit. It could be  a create, publish, delete, update, view etc, so what about calling it something more general like "addEntry" ?
I also added the option to sepcify an action name.
Do you think this is a good idea, or should we stick to the UML?

Item history

---

src/AdminLink.php
src/Concerns/RegistersMenuWidgetLinks.php
src/Contracts/AdminLink.php
src/RouteAdminLink.php
tests/Feature/Fakes/UserlandController.php
tests/Feature/Fakes/UserlandServiceProvider.php
tests/Feature/RouteAdminLinkTest.php
tests/Feature/UserlandControllerTest.php
tests/Unit/AdminLinkTest.php

This PR contains substantial changes related to `AdminLink` and its implementations.
The main reason for the rework is because `RouteAdminLink` needs to handle [route parameters for named routes](https://laravel.com/docs/5.7/urls#urls-for-named-routes).
But it also does this to get there:
1. It switches argument orders for many methods. The idea is to keep the arguments that are common across methods/implementation first, then required arguments, and of course last optional arguments.
The big thing here is that `$name` is now provided first to `AdminLink` constructors, followed by any params required to generate the actual url.
2. It adds fluent methods `withDescription()` and `withRouteParameters()` so that parameters that were optional in the constructor can be added later, regardless …

Admin links rework

---

src/Concerns/AuthorizesWithAbility.php
src/Contracts/AuthorizesWithAbility.php
tests/Feature/AuthorizesWithAbilityTest.php

This PR makes the `AuthorizesWithAbility` implementations serializable by registering any Guard using a guard name as a string instead of an object.
Also, `SerializesModels` is used if a single argument is given with the gate or policy name. Unfortunately the model serialization does not work if multiple arguments are to be given to the "ability", but that's a pretty rare case. Most cases just have a single model to check, so we'll have to leave it that way for now. The problem is that `SerializesModels` only serializes models if they're in a declared property of the class, not if they're in an array or other structure deeper in the object.

Serialization of AuthorizesWithAbility

---

.gitattributes
.gitignore
.travis.yml
DEVELOPMENT.md
composer.json
phpcs.xml
phpcs.xml.dist
routes/admin.php
src/AdminWidgetManager.php
src/Concerns/AuthorizesWithAbility.php
src/Concerns/RegistersMenuWidgetLinks.php
src/Http/Controllers/Auth/ForgotPasswordController.php
src/Providers/KontourServiceProvider.php
src/RecentVisitsRepository.php
src/Widgets/MenuWidget.php

This PR adds a a configuration and dev-dependency for PHP CodeSniffer enforcing the PSR2 coding standard + run before phpunit by Travis CI.
Usage documentation is included in `DEVELOPMENT.md`.
This PR also includes fixes for those few PSR2 deviations that were found in the code base, so that the build passes.

Use PHP CodeSniffer

---

resources/views/forms/input.blade.php
src/Auth/AdminUser.php

This PR makes password fields not refill their values by default.
It also stops password fields in admin users from being "fillable".

Blank passwords

---

src/Http/Controllers/Auth/ResetPasswordController.php

When these methods are missing the default guard and password broker are used and password resets didn't work through the final step when a special admin guard had been configured.

Add missing broker and guard methods

---

src/Concerns/DispatchesAdminToolEvents.php
src/Concerns/ResolvesAdminUser.php
src/Widgets/CrumbtrailWidget.php
src/Widgets/MenuWidget.php
src/Widgets/PersonalRecentVisitsWidget.php
src/Widgets/TeamRecentVisitsWidget.php
src/Widgets/UserAccountWidget.php
tests/Feature/AuthenticationTest.php
tests/Feature/Fakes/UserlandController.php
tests/Feature/PasswordResetTest.php
tests/Feature/UserlandControllerTest.php
tests/IntegrationTestSetupTrait.php

This PR makes sure the current user can access admin links (in widgets etc) before printing them.
To arrive at that I created a trait `ResolvesAdminUsers` that has a method `adminUser()`.
This trait is now used everywhere where the current user is needed.
The tests had to be updated to use a specific admin guard, not the default Laravel web guard, and when doing that I added a specific password reset too.

Display authorized links only

---

.travis.yml
DEVELOPMENT.md
README.md
composer.json
src/Http/Middleware/AuthenticateAdmin.php
tests/Feature/AuthenticationTest.php

This PR makes the auth checking middleware throw an exception if the user is not an implementation of the kontour admin user contract.
To arrive at that we are dropping support for Laravel 5.6, to use features of Laravel's auth middleware in 5.7.
And to test the exception we pull in `timacdonald/log-fake` that can... fake the logger 😄

Require user to implement AdminUser contract

---

config/kontour.php
src/RecentVisitsRepository.php
src/Widgets/PersonalRecentVisitsWidget.php
src/Widgets/TeamRecentVisitsWidget.php

- Refactor visit cache storage to save a collection for each user, along with a cached array of all user ids.
- Add config for max number of visited links in widgets
- Remove duplicate links per user in cache storage instead of filtering duplicates in the widget

Fix recent widgets

---

resources/views/forms/checkbox.blade.php
resources/views/forms/checkboxes.blade.php
resources/views/forms/groups/checkbox.blade.php
resources/views/forms/groups/checkboxes.blade.php
resources/views/forms/groups/input.blade.php
resources/views/forms/groups/multiselect.blade.php
resources/views/forms/groups/radiobuttons.blade.php
resources/views/forms/groups/select.blade.php
resources/views/forms/groups/textarea.blade.php
resources/views/forms/input.blade.php
resources/views/forms/multiselect.blade.php
resources/views/forms/partials/groupAttributes.blade.php
resources/views/forms/radiobuttons.blade.php
resources/views/forms/select.blade.php
resources/views/forms/textarea.blade.php

This PR further improves the reusability of form templates by breaking the logic out for each "group", consisting of a form control, its wrapper and label.
This makes it possible to just `@include` the group in a local project and send along/merge any label or control attributes one wants to add, e.g. bootstrap classes.

Improve form templates, again

---

src/Concerns/AuthorizesAdminRequests.php
src/Concerns/AuthorizesWithAbility.php
src/Contracts/AuthorizesWithAbility.php

Remove call to parseAbilityAndArguments as it only works directly in controller method anyway.
If the ability is not specified, skip the auth and just return the link, effectively just triggering the visited event.

Skip authorization if ability is null

---

resources/views/forms/elements/label.blade.php
resources/views/forms/groups/checkbox.blade.php
resources/views/forms/groups/checkboxes.blade.php
resources/views/forms/groups/input.blade.php
resources/views/forms/groups/multiselect.blade.php
resources/views/forms/groups/radiobuttons.blade.php
resources/views/forms/groups/select.blade.php
resources/views/forms/groups/textarea.blade.php
resources/views/forms/partials/attribute.blade.php
resources/views/forms/partials/checkableOption.blade.php
resources/views/forms/partials/checkableOptions.blade.php
resources/views/forms/partials/errors.blade.php
resources/views/forms/partials/inputAttributes.blade.php
tests/Feature/FormViewTests/CheckboxesTest.php
tests/Feature/FormViewTests/InputAttributesTest.php
tests/Feature/FormViewTests/InputTest.php
tests/Feature/FormViewTests/LabelTest.php
tests/Feature/FormViewTests/MultiselectTest.php

This PR makes possible to use the form templates with dot-notation to nest form data in arrays.
You can now `@include` an input with `'name' => 'dot.notation'` and that will result in `name="dot[notation]"` being printed in HTML with a nice humanized label "Dot notation". The error MessageBag in Laravel already references inputs with this notation, so that keeps working as usual.
It also makes sure an input can display errors from more than one validation field which is useful for `multiple` type inputs where you want to print any errors related to the `field` but also to `field.*` next to the same input.
The PR also adds a little functionality for checkbox multiselects, where if a specific checkbox has an error, then that error is printed next to it, and if not each checkbox gets …

Array inputs with dot-notation

---

README.md
resources/views/forms/groups/multiselect.blade.php
resources/views/forms/partials/checkableOption.blade.php
resources/views/forms/partials/checkableOptions.blade.php
resources/views/forms/partials/inputAttributes.blade.php
tests/Feature/FormViewTests/CheckboxTest.php
tests/Feature/FormViewTests/CheckboxesTest.php
tests/Feature/FormViewTests/InputAttributesTest.php
tests/Feature/FormViewTests/InputTest.php
tests/Feature/FormViewTests/MultiselectTest.php
tests/Feature/FormViewTests/RadiobuttonsTest.php
tests/Feature/FormViewTests/SelectTest.php
tests/Feature/FormViewTests/TextareaTest.php

This PR makes it possible to declare an `$autofocusControlId` for a form and that input (only) will get the autofocus attribute.
To get there I also switched from generating html ids like `test[a_value]` to `test.0` so that the id's correspond to the keys in Laravel's error bag.
Closes #67

Input autofocus

---

resources/views/auth/passwords/email.blade.php
src/Http/Controllers/Auth/ForgotPasswordController.php
tests/Feature/PasswordResetTest.php

This PR makes use of the `MessageWidget` to display status message to user after password reset email has been sent.
Tests have been updated to make sure the message is displaying properly.

Use message widget in password reset

---

README.md
resources/views/forms/elements/checkbox.blade.php
resources/views/forms/elements/input.blade.php
resources/views/forms/groups/checkboxes.blade.php
resources/views/forms/groups/multiselect.blade.php
resources/views/forms/groups/radiobuttons.blade.php
resources/views/forms/groups/select.blade.php
resources/views/forms/groups/textarea.blade.php
tests/Feature/FormViewTests/CheckboxTest.php
tests/Feature/FormViewTests/CheckboxesTest.php
tests/Feature/FormViewTests/InputTest.php
tests/Feature/FormViewTests/MultiselectTest.php
tests/Feature/FormViewTests/RadiobuttonsTest.php
tests/Feature/FormViewTests/SelectTest.php
tests/Feature/FormViewTests/TextareaTest.php

This PR updates the form input templates to only repopulate forms whenever there are errors present in the errors message bag.
For a first time page-load there is no difference as there are no errors and no old data anyway.
This makes it possible to have multiple forms on the same page without them repopulating each other.
Devs only need to pass different error bags into different forms.
Closes #114

Only use old data in forms when errors are present

---

.gitignore
.travis.yml
DEVELOPMENT.md
composer.json
database/factories/UserFactory.php
resources/views/forms/elements/label.blade.php
tests/Feature/AuthenticationTest.php
tests/Feature/ElementViewTests/TimeTest.php
tests/Feature/UserlandServiceProviderTest.php

This PR allows Kontour to be installed with Laravel 6.
To get there the deprecated Laravel string helpers and `Lang::trans` had to be replaced.
Tests and test-related dependencies have been updated to get rid of all warnings.

Support Laravel 6

---

.travis.yml
DEVELOPMENT.md
README.md
composer.json

This PR drops support for Laravel 5.7 and with it PHP 7.1
The reason we had to do this is that Nexmo changed their packages in some weird way, see https://github.com/laravel/framework/issues/30257

Drop support for Laravel 5.7 and PHP 7.1

---

README.md
config/kontour.php
src/Providers/KontourServiceProvider.php

This PR adds a `register_routes` config value so that consumers of Kontour may let the service provider run, but opt out of registration of the default auth and dashboard routes.
This is useful if you just want to use some part of Kontour, for example the form view templates.
Closes #124

Config for route registration

---

resources/views/forms/partials/inputAttributes.blade.php
tests/Feature/FormViewTests/InputAttributesTest.php

This PR fixes an issue where no space was echoed between inputs' `name` and `id` attribute like this: `name="a"id="b"` 😱 
Tests have been updated to catch this problem.

Test & fix spacing between input attributes

---

resources/views/auth/login.blade.php
resources/views/auth/passwords/email.blade.php
resources/views/auth/passwords/reset.blade.php
resources/views/forms/email.blade.php
tests/Feature/FormViewTests/EmailTest.php

This PR adds a new form template for `email` type inputs. It's "extending" the normal input template, but it adds some sensible default attributes:
- `type="email"`
- `name="email"`
- `autocomplete="email"`
- `autocapitalize="none"`
- `autocorrect="off"` (for Safari)
Closes #137

Create email input

---

docs/form-templates.md
resources/views/forms/partials/inputAttributes.blade.php
tests/Feature/FormViewTests/InputAttributesTest.php

This PR removes the dedicated `$ariaDescribedById` option for inputs and instead encourages use of `$controlAttributes['aria-describedby']`. This is ment to reduce the number of special options for inputs so that there are not conflicting ways of achieving the same thing.
After this, the only special parameters for inputs are `$name` and `$placeholder`... because they are treated differently in different inputs.
This also prepends any error description element id to `aria-describedby` instead of overwriting it so one can have multiple descriptive elements for an input.
Closes #152

Improve aria-describedby

---

resources/views/forms/partials/errors.blade.php
resources/views/widgets/crumbtrail.blade.php
resources/views/widgets/itemHistory.blade.php
resources/views/widgets/menu.blade.php
resources/views/widgets/message.blade.php
resources/views/widgets/personalRecentVisits.blade.php
resources/views/widgets/teamRecentVisits.blade.php
tests/Feature/UserlandControllerTest.php

This PR adds `role="list"` to all `<ul>` and `<ol>` elements to keep list-semantics in Safari.
See https://www.scottohara.me/blog/2019/01/12/lists-and-safari.html#a-new-alternative
Closes #142

Keep list semantics for unstyled lists

---

README.md
docs/tool-creation.md

This PR splits the docs to focus on Install and configuration in the readme, and tool creation in the `docs/` directory.
Also does general improvements to wording and code examples.
See #87 
Closes #164

Break out and improve docs for tool creation

---

resources/views/dashboard/laravelConfig.blade.php

The kontour index page displays app config values and this PR makes those print in monospace font when booleans or numbers.
Closes #156

Display booleans and numbers nicely

---

phpunit.xml.dist
tests/Feature/FormViewTests/MultiselectTest.php
tests/Feature/FormViewTests/SelectTest.php
tests/IntegrationTest.php

`assertRegExp()` and `assertNotRegExp()` are deprecated and will be removed in PHPUnit 10.
We're using them quite a lot in our tests (more than a 100 times) and although it can be refactored to `assertMatchesRegularExpression()` it's better to try not using them at all. The tests become very hard to read when all it does is matching a massive regex.
So I've created a method that splits a string between `>` and `<` so we get an array of tags. Then more precise assertions can be made on those tags, instead of having them all in one big regex.
This PR contains updates to three tests (that were especially brittle), now using the new split instead of regex.
So this is just a start of a much bigger refactor, with the end goal of replacing the other 129 occurrences of regexp assertions with …

Start replacing regex assertions in tests

---

resources/views/auth/login.blade.php
resources/views/buttons/hamburger.blade.php
resources/views/buttons/logout.blade.php
resources/views/layouts/master.blade.php
tests/Browser/AuthenticationTest.php
tests/Feature/AuthenticationTest.php

This is to avoid conflicts with userland translation files with single-word names.
See https://github.com/kontenta/kontour/issues/178
Closes #191

Add two-word verbs for actions

---

.travis.yml
DEVELOPMENT.md
README.md
composer.json

Add support for Laravel 8.
We need to drop support for PHP `7.2` for the next version of Kontour because the tests are using `laravel/legacy-factories` that only support PHP `7.3`.
See #190

Support Laravel 8

---

phpunit.xml.dist
resources/views/layouts/html.blade.php
tests/DuskTest.php

This PR makes the language code correct if the app locale has an underscore, it's replaced with a dash. See [BCP47 at MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/lang).
Example: `en_US` becomes `en-US` in the hTML attribute.
Fixes #195

Replace underscores in html lang attributes

---

.github/workflows/run-tests.yml
.github/workflows/tests.yml
README.md
composer.json
tests/Browser/source/.gitignore
tests/Feature/AdminLinkTest.php
tests/Feature/AdminVisitTest.php
tests/Feature/AuthenticationTest.php
tests/Feature/AuthorizesWithAbilityTest.php
tests/Feature/ElementViewTests/TimeTest.php
tests/Feature/FormViewTests/CheckboxTest.php
tests/Feature/FormViewTests/CheckboxesTest.php
tests/Feature/FormViewTests/EmailTest.php
tests/Feature/FormViewTests/ErrorsTest.php
tests/Feature/FormViewTests/InputAttributesTest.php
tests/Feature/FormViewTests/InputTest.php
tests/Feature/FormViewTests/LabelTest.php
tests/Feature/FormViewTests/MultiselectTest.php
tests/Feature/FormViewTests/RadiobuttonsTest.php
tests/Feature/FormViewTests/SelectTest.php
tests/Feature/FormViewTests/TextareaTest.php
tests/IntegrationTestSetupTrait.php

This PR adds support for Laravel 9 and drops support for Laravel 8 for the next release. See #198
- Removes the PHP version requirement from `composer.json` as it's already enforced by `laravel/framework`.
- Replaces deprecated PhpUnit regex assertions.
- Removes `__wakeup()` call (that was removed in PHP 8) from tests.
This PR includes setting up a new test-runner for PR:s with GitHub Actions. Closes #200

Support Laravel 9
